# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import state_service_pb2 as state__service__pb2


class StateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamState = channel.stream_stream(
                '/state.StateService/StreamState',
                request_serializer=state__service__pb2.GetStateRequest.SerializeToString,
                response_deserializer=state__service__pb2.State.FromString,
                )


class StateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamState(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamState': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=state__service__pb2.GetStateRequest.FromString,
                    response_serializer=state__service__pb2.State.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'state.StateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/state.StateService/StreamState',
            state__service__pb2.GetStateRequest.SerializeToString,
            state__service__pb2.State.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
